sudo: required
# language: generic
services:
  - docker

before_install:
  - docker build -t rodrigoillera/docker-react -f Dockerfile.dev .

script:
  - docker run rodrigoillera/docker-react npm run test -- --coverage
#  - docker run -e CI=true rodrigoillera/docker-react npm run test